//! Embedded public platform icons with provenance retained beside the asset set.

macro_rules! icon {
    ($filename:literal) => {
        Some(&include_bytes!(concat!("../../web/public/platform-icons/", $filename))[..])
    };
}

pub(super) fn get(path: &str) -> Option<&'static [u8]> {
    let filename = path.strip_prefix("platform-icons/")?;
    match filename {
        "3do.png" => icon!("3do.png"),
        "amigacd32.png" => icon!("amigacd32.png"),
        "atarijaguar.png" => icon!("atarijaguar.png"),
        "atarijaguarcd.png" => icon!("atarijaguarcd.png"),
        "atarilynx.png" => icon!("atarilynx.png"),
        "cdimono1.png" => icon!("cdimono1.png"),
        "colecovision.png" => icon!("colecovision.png"),
        "dreamcast.png" => icon!("dreamcast.png"),
        "famicom.png" => icon!("famicom.png"),
        "fds.png" => icon!("fds.png"),
        "gamegear.png" => icon!("gamegear.png"),
        "gb.png" => icon!("gb.png"),
        "gba.png" => icon!("gba.png"),
        "gbc.png" => icon!("gbc.png"),
        "gc.png" => icon!("gc.png"),
        "genesis.png" => icon!("genesis.png"),
        "intellivision.png" => icon!("intellivision.png"),
        "mastersystem.png" => icon!("mastersystem.png"),
        "megacd.png" => icon!("megacd.png"),
        "megacdjp.png" => icon!("megacdjp.png"),
        "megadrive.png" => icon!("megadrive.png"),
        "n3ds.png" => icon!("n3ds.png"),
        "n64.png" => icon!("n64.png"),
        "n64dd.png" => icon!("n64dd.png"),
        "nds.png" => icon!("nds.png"),
        "neogeo.png" => icon!("neogeo.png"),
        "neogeocd.png" => icon!("neogeocd.png"),
        "nes.png" => icon!("nes.png"),
        "ngp.png" => icon!("ngp.png"),
        "ngpc.png" => icon!("ngpc.png"),
        "pcengine.png" => icon!("pcengine.png"),
        "pcenginecd.png" => icon!("pcenginecd.png"),
        "pcfx.png" => icon!("pcfx.png"),
        "ps2.png" => icon!("ps2.png"),
        "ps3.png" => icon!("ps3.png"),
        "ps4.png" => icon!("ps4.png"),
        "psp.png" => icon!("psp.png"),
        "psvita.png" => icon!("psvita.png"),
        "psx.png" => icon!("psx.png"),
        "satellaview.png" => icon!("satellaview.png"),
        "saturn.png" => icon!("saturn.png"),
        "saturnjp.png" => icon!("saturnjp.png"),
        "sega32x.png" => icon!("sega32x.png"),
        "sega32xjp.png" => icon!("sega32xjp.png"),
        "sega32xna.png" => icon!("sega32xna.png"),
        "segacd.png" => icon!("segacd.png"),
        "sfc.png" => icon!("sfc.png"),
        "sgb.png" => icon!("sgb.png"),
        "snes.png" => icon!("snes.png"),
        "snesna.png" => icon!("snesna.png"),
        "supergrafx.png" => icon!("supergrafx.png"),
        "switch.png" => icon!("switch.png"),
        "tg-cd.png" => icon!("tg-cd.png"),
        "tg16.png" => icon!("tg16.png"),
        "virtualboy.png" => icon!("virtualboy.png"),
        "wii.png" => icon!("wii.png"),
        "wiiu.png" => icon!("wiiu.png"),
        "win.png" => icon!("win.png"),
        "wonderswan.png" => icon!("wonderswan.png"),
        "wonderswancolor.png" => icon!("wonderswancolor.png"),
        "xbox.png" => icon!("xbox.png"),
        "xbox360.png" => icon!("xbox360.png"),
        _ => None,
    }
}
